// ==UserScript==
// @name         iphone Stock Checker
// @namespace    http://tampermonkey.net/
// @version      0.4
// @description  try to take over the world!
// @author       @mersahin
// @require      https://code.jquery.com/jquery-3.6.3.js
// @match        https://reserve-prime.apple.com/TR/tr_TR/reserve/A/availability?iUP=N
// @icon         https://www.google.com/s2/favicons?sz=64&domain=apple.com
// @grant        GM_notification
// ==/UserScript==

(function() {
  'use strict';
  function telegram(message) {
    var token = "<token>";
    var chat_id = -1; // test


    var url = `https://api.telegram.org/bot${token}/sendMessage?chat_id=${chat_id}&text=${message}`;

    var oReq = new XMLHttpRequest();
    oReq.open("GET", url, true);
    oReq.send();
  }

  setInterval(function() {
    $.get("https://reserve-prime.apple.com/TR/tr_TR/reserve/A/availability.json", function(data) {
      var datas = {
        "subfamilies": [
          {
            "id": "1380585647",
            "name": "iPhone 14 Pro Max",
            "localizedName": "iPhone 14 Pro Max",
            "sortOrder": "2"
          },
          {
            "id": "1217516811",
            "name": "iPhone 14 Pro",
            "localizedName": "iPhone 14 Pro",
            "sortOrder": "1"
          },
        ],
        "carriers": [
          {
            "id": "488263106",
            "name": "Sim-free",
            "groups": [
              "613821957",
            ]
          },
        ],
        "groups": [
          {
            "id": "613821957",
            "name": "iPhone14Pro",
            "description": "iPhone14Pro",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "carriers": [
              "Sim-free",
            ]
          },
        ],
        "products": [
          {
            "partNumber": "MQ1W3TU\/A",
            "description": "iPhone 14 Pro 512 GB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "512GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "47.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422371",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422371",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQAM3TU\/A",
            "description": "iPhone 14 Pro Max 512 GB Derin Mor",
            "color": "Derin Mor",
            "capacity": "512GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "51.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576364",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576364",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQAJ3TU\/A",
            "description": "iPhone 14 Pro Max 512 GB Altın Rengi",
            "color": "Altın",
            "capacity": "512GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "51.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576380",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576380",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ9P3TU\/A",
            "description": "iPhone 14 Pro Max 128 GB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "128GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "43.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576357",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576357",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ0T3TU\/A",
            "description": "iPhone 14 Pro 256 GB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "256GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "42.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422874",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422874",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQC43TU\/A",
            "description": "iPhone 14 Pro Max 1 TB Altın Rengi",
            "color": "Altın",
            "capacity": "1TB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "57.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576380",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576380",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ2G3TU\/A",
            "description": "iPhone 14 Pro 1 TB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "1TB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "53.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422874",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422874",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ183TU\/A",
            "description": "iPhone 14 Pro 256 GB Altın Rengi",
            "color": "Altın",
            "capacity": "256GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "42.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422297",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422297",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQC33TU\/A",
            "description": "iPhone 14 Pro Max 1 TB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "1TB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "57.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576311",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576311",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQAF3TU\/A",
            "description": "iPhone 14 Pro Max 512 GB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "512GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "51.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576357",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576357",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ103TU\/A",
            "description": "iPhone 14 Pro 256 GB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "256GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "42.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422371",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422371",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ023TU\/A",
            "description": "iPhone 14 Pro 128 GB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "128GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "39.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422371",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422371",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ9Q3TU\/A",
            "description": "iPhone 14 Pro Max 128 GB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "128GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "43.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576311",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576311",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ9V3TU\/A",
            "description": "iPhone 14 Pro Max 256 GB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "256GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "46.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576311",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576311",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MPXV3TU\/A",
            "description": "iPhone 14 Pro 128 GB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "128GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "39.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422874",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422874",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ2N3TU\/A",
            "description": "iPhone 14 Pro 1 TB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "1TB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "53.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422371",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422371",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ0G3TU\/A",
            "description": "iPhone 14 Pro 128 GB Derin Mor",
            "color": "Derin Mor",
            "capacity": "128GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "39.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422362",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422362",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ2V3TU\/A",
            "description": "iPhone 14 Pro 1 TB Altın Rengi",
            "color": "Altın",
            "capacity": "1TB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "53.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422297",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422297",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ323TU\/A",
            "description": "iPhone 14 Pro 1 TB Derin Mor",
            "color": "Derin Mor",
            "capacity": "1TB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "53.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422362",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422362",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ9U3TU\/A",
            "description": "iPhone 14 Pro Max 256 GB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "256GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "46.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576357",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576357",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQC23TU\/A",
            "description": "iPhone 14 Pro Max 1 TB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "1TB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "57.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576357",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576357",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ9X3TU\/A",
            "description": "iPhone 14 Pro Max 256 GB Derin Mor",
            "color": "Derin Mor",
            "capacity": "256GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "46.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576364",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576364",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ9R3TU\/A",
            "description": "iPhone 14 Pro Max 128 GB Altın Rengi",
            "color": "Altın",
            "capacity": "128GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "43.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576380",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576380",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQC53TU\/A",
            "description": "iPhone 14 Pro Max 1 TB Derin Mor",
            "color": "Derin Mor",
            "capacity": "1TB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "57.199,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576364",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576364",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQAH3TU\/A",
            "description": "iPhone 14 Pro Max 512 GB Gümüş Rengi",
            "color": "Gümüş",
            "capacity": "512GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "51.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576311",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-silver-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576311",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ293TU\/A",
            "description": "iPhone 14 Pro 512 GB Derin Mor",
            "color": "Derin Mor",
            "capacity": "512GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "47.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422362",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422362",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ1F3TU\/A",
            "description": "iPhone 14 Pro 256 GB Derin Mor",
            "color": "Derin Mor",
            "capacity": "256GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "42.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422362",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422362",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ1M3TU\/A",
            "description": "iPhone 14 Pro 512 GB Uzay Siyahı",
            "color": "Uzay Siyahı",
            "capacity": "512GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "47.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422874",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-spaceblack-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422874",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ083TU\/A",
            "description": "iPhone 14 Pro 128 GB Altın Rengi",
            "color": "Altın",
            "capacity": "128GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "39.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422297",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422297",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ9T3TU\/A",
            "description": "iPhone 14 Pro Max 128 GB Derin Mor",
            "color": "Derin Mor",
            "capacity": "128GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "43.999,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576364",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-deeppurple-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576364",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
          {
            "partNumber": "MQ233TU\/A",
            "description": "iPhone 14 Pro 512 GB Altın Rengi",
            "color": "Altın",
            "capacity": "512GB",
            "screenSize": '6.1 inç ekran<sup>1<\/sup>',
            "price": "47.899,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364422297",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364422297",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1217516811",
            "subfamily": "iPhone 14 Pro"
          },
          {
            "partNumber": "MQ9W3TU\/A",
            "description": "iPhone 14 Pro Max 256 GB Altın Rengi",
            "color": "Altın",
            "capacity": "256GB",
            "screenSize": '6.7 inç ekran<sup>1<\/sup>',
            "price": "46.599,00 TL",
            "installmentPrice": "",
            "installmentPeriod": "0",
            "paymentPrice": "",
            "paymentInstallments": "",
            "iUPPrice": "",
            "iUPInstallments": "2",
            "colorSortOrder": "",
            "swatchImage": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select_SW_COLOR?wid=16&hei=16&fmt=jpeg&qlt=90&.v=1663364576380",
            "image": "https:\/\/store.storeimages.cdn-apple.com\/4668\/as-images.apple.com\/is\/iphone-14-pro-max-gold-select?wid=512&hei=512&fmt=png-alpha&.v=1663364576380",
            "contractEnabled": true,
            "unlockedEnabled": true,
            "groupID": "613821957",
            "groupName": "iPhone14Pro",
            "subfamilyID": "1380585647",
            "subfamily": "iPhone 14 Pro Max"
          },
        ]
      };
      var stores = [
        {
          "R583": "Z"
        },
        {
          "R724": "B"
        },
        {
          "R588": "A"
        }
      ]
      $('#form-alert-stage').html("")

      for (let storeId in data.stores) {
        let phones = data.stores[storeId];
        let magaza = stores.filter(s=> Object.keys(s) == storeId)[0][storeId]

        for (let phoneId in phones) {
          let phone = phones[phoneId]
          if (phone.availability.unlocked) {
            console.log("unlocked")
            let telefon = datas.products.filter(s=> s.partNumber == phoneId)[0]

            if(telefon.subfamily.indexOf("Max") != -1) // Max varsa
            {
              console.log("max")
              // GM_notification ( {title: 'Pro max Stokta', text: 'MURAT'} );
              // if (telefon.color.indexOf("Mor") != -1) // Mor Renkli Varsa
              // {
              // GM_notification ( {title: 'Pro max MOR Stokta', text: 'MURAT'} );
              // }
              telegram(`⭐ Max Var! ${telefon.capacity} ${telefon.color} ${telefon.color.indexOf("Gümü") != -1?"⚪":""}${telefon.color.indexOf("Mor") != -1?"🟣":""}${telefon.color.indexOf("Uzay") != -1?"⚫":""}${telefon.color.indexOf("Alt") != -1?"🟡":""} ${magaza}`)
            } else
            {
              if( telefon.capacity.indexOf("128") != -1 || telefon.capacity.indexOf("256") != -1)
              {
                console.log("128")

                telegram(`Pro Var! ${telefon.capacity} ${telefon.color} ${telefon.color.indexOf("Gümü") != -1?"⚪":""}${telefon.color.indexOf("Mor") != -1?"🟣":""}${telefon.color.indexOf("Uzay") != -1?"⚫":""}${telefon.color.indexOf("Alt") != -1?"🟡":""} ${magaza}`)
              }
            }

            // buradan asagidaki kisim apple web sayfasina yazilari eklemek icin.
            let msg = `
          ${telefon.subfamily.indexOf("Max") != -1 ? "<span style='color:red'>⭐ "+telefon.subfamily+"</span>":""}
          ${telefon.capacity}
          ${telefon.color.indexOf("Mor") != -1 ? "<span style='background:purple; color:white;'>🟣 "+telefon.color+"</span>":""}
          ${telefon.color.indexOf("Alt") != -1 ? "<span style='background:gold;'>🟡 "+telefon.color+"</span>":""}
          ${telefon.color.indexOf("Gümü") != -1 ? "<span style='background:gray; color:white;'>⚪ "+telefon.color+"</span>":""}
          ${telefon.color.indexOf("Uzay") != -1 ? "<span style='background:black; color:white;'>⚫ "+telefon.color+"</span>":""}
          ${telefon.color.indexOf("asdasdasd") != -1 ? telefon.color:""}
          ${telefon.color}
          >>>>
          ${magaza} <br>`;
            //console.log(msg)
            $('#form-alert-stage').css("font-family","monospace")
            $('#form-alert-stage').append(msg)
            /*
          {
    "partNumber": "MQ1M3TU/A",
    "description": "iPhone 14 Pro 512 GB Uzay Siyahı",
    "color": "Uzay Siyahı",
    "capacity": "512GB",
    "screenSize": "6.1 inç ekran<sup>1</sup>",
    "price": "47.899,00 TL",
    "installmentPrice": "",
    "installmentPeriod": "0",
    "paymentPrice": "",
    "paymentInstallments": "",
    "iUPPrice": "",
    "iUPInstallments": "2",
    "colorSortOrder": "",
    "contractEnabled": true,
    "unlockedEnabled": true,
    "groupID": "613821957",
    "groupName": "iPhone14Pro",
    "subfamilyID": "1217516811",
    "subfamily": "iPhone 14 Pro"
}
          */
          }
        }
      }
    })
  }, 5000)
})();
